const imageMapHTML = `
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="draw6.jpg" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Green Tongs" title="Green Tongs" href="" coords="597,568,672,601,695,642,739,681,886,728,982,769,1082,808,1139,800,1304,859,1250,920,1089,862,1083,840,878,776,785,724,689,705,604,734,541,719,493,669,488,625,522,575,560,567" shape="poly">
    <area target="" alt="Rolling Pin" title="Rolling Pin" href="" coords="378,964,413,987,449,961,548,968,675,978,959,972,1155,995,1216,994,1243,1032,1239,1071,1206,1086,1028,1094,825,1094,590,1091,433,1088,408,1049,378,1063,340,1053,343,1002" shape="poly">
    <area target="" alt="Pizza Cutter" title="Pizza Cutter" href="" coords="739,502,801,493,852,544,823,613,775,628,729,608,692,618,666,588" shape="poly">
    <area target="" alt="" title="" href="" coords="" shape="0">
</map>
`;

function convertImageMapToJson(imageMapHTML) {
  const imgSrcMatch = imageMapHTML.match(/<img src="([^"]+)"/);
  const imgSrc = imgSrcMatch ? imgSrcMatch[1] : "";

  const areaMatches = [
    ...imageMapHTML.matchAll(
      /<area[^>]+title="([^"]+)"[^>]+coords="([^"]+)"[^>]*>/g
    ),
  ];

  const utensils = areaMatches.map((areaMatch) => {
    const name = areaMatch[1];
    const coords = areaMatch[2];

    return {
      name: name,
      mapBoundary: coords,
      descriptions: [name],
    };
  });

  return {
    img: imgSrc,
    source: "",
    utensils: utensils,
  };
}

const utensilData = convertImageMapToJson(imageMapHTML);
console.log(JSON.stringify(utensilData, null, 2));
