const imageMapHTML = `
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="draw5.jpeg" usemap="#image-map">

<map name="image-map">
    <area target="" alt="grey peeler" title="grey peeler" href="" coords="1102,1767,1074,1959,1167,2048,1142,2169,1099,2233,1120,2565,1206,2746,1391,2735,1519,2515,1555,2187,1498,2080,1608,1941,1612,1727,1530,1713,1177,1738" shape="poly">
    <area target="" alt="can opener" title="can opener" href="" coords="1544,2390,2327,2265,2854,2180,3068,2276,3054,2415,2922,2432,2958,2561,2951,2718,2883,2882,2723,2593,2477,2611,1654,2792,1359,2831,1259,2764,1330,2753,1419,2732,1455,2639,1530,2508" shape="poly">
    <area target="" alt="orange peeler" title="orange peeler" href="" coords="1647,1752,1726,1738,1897,1809,2000,1884,2153,1859,2524,1827,2744,1852,2833,1923,2773,2041,2492,2105,2242,2087,2068,2052,1971,2105,1843,2198,1683,2269,1597,2219" shape="poly">
    <area target="" alt="green peeler" title="green peeler" href="" coords="1330,413,1455,1040,1633,1147,1697,1400,1263,1500,1220,1261,1341,1061,1206,438" shape="poly">
    <area target="" alt="ice cream scoop" title="ice cream scoop" href="" coords="1516,203,1327,232,1316,317,1416,438,1562,456,1715,363,2809,427,2826,331,2630,264" shape="poly">
    <area target="" alt="scissors" title="scissors" href="" coords="1516,620,1669,908,1907,1254,1868,1378,1879,1535,1929,1692,2000,1777,2103,1831,2292,1834,2427,1767,2630,1606,2584,1435,2424,1254,2203,1154,2085,1140,1701,851,1640,723" shape="poly">
    <area target="" alt="garlic press" title="garlic press" href="" coords="1669,609,1622,645,1708,837,1865,965,1964,955,2670,1396,2791,1443,2969,1247,2851,1129,2175,712,2032,613,1793,602" shape="poly">
</map>
`;

function convertImageMapToJson(imageMapHTML) {
  const imgSrcMatch = imageMapHTML.match(/<img src="([^"]+)"/);
  const imgSrc = imgSrcMatch ? imgSrcMatch[1] : "";

  const areaMatches = [
    ...imageMapHTML.matchAll(
      /<area[^>]+title="([^"]+)"[^>]+coords="([^"]+)"[^>]*>/g
    ),
  ];

  const utensils = areaMatches.map((areaMatch) => {
    const name = areaMatch[1];
    const coords = areaMatch[2];

    return {
      name: name,
      mapBoundary: coords,
      descriptions: [name],
    };
  });

  return {
    img: imgSrc,
    source: "",
    utensils: utensils,
  };
}

const utensilData = convertImageMapToJson(imageMapHTML);
console.log(JSON.stringify(utensilData, null, 2));
